name: GitHub Page Deploy

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'
          extended: true

      - name: Build Hugo
        run: |
          hugo --gc --minify --cleanDestinationDir

      - name: Deploy Hugo to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          BLOG_DEPLOY: ${{ secrets.BLOG_DEPLOY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
